const VIEW_CONFIGS = Object.freeze({
    home: {
        styles: [
            '/css/pages/storefront/home.css',
            '/css/shared/dropdown.css',
            '/css/shared/product-card.css',
            '/css/shared/pagination.css',
            '/css/shared/empty-state.css',
            '/css/shared/tooltip.css',
        ],
        entryScript: '/js/pages/storefront/home/home.js',
    },
    product: {
        styles: [
            '/css/pages/storefront/product/product.css',
            '/css/pages/storefront/product/gallery.css',
            '/css/pages/storefront/product/info.css',
            '/css/pages/storefront/product/reviews.css',
            '/css/shared/dropdown.css',
            '/css/shared/product-card.css',
            '/css/shared/pagination.css',
            '/css/shared/empty-state.css',
            '/css/pages/storefront/product/lightbox.css',
        ],
        entryScript: '/js/pages/storefront/product/product.js',
    },
    cart: {
        styles: [
            '/css/pages/storefront/checkout-header.css',
            '/css/pages/storefront/cart.css',
            '/css/shared/empty-state.css',
        ],
        entryScript: '/js/pages/storefront/cart/cart.js',
        header: {
            path: '../pages/storefront/partials/header-checkout-page',
            data: { pageName: 'Giỏ Hàng', showSearch: true },
        },
    },
    checkout: {
        styles: [
            '/css/pages/storefront/checkout-header.css',
            '/css/shared/address-card.css',
            '/css/shared/empty-state.css',
            '/css/pages/storefront/checkout/checkout-address-selector.css',
            '/css/pages/storefront/checkout/checkout.css',
        ],
        entryScript: '/js/pages/storefront/checkout/checkout.js',
        header: {
            path: '../pages/storefront/partials/header-checkout-page',
            data: { pageName: 'Thanh Toán', showSearch: false },
        },
    },
    user: {
        styles: [
            '/css/shared/base.css',
            '/css/shared/grid.css',
            '/css/shared/button.css',
            '/css/shared/avatar-placeholder.css',
            '/css/shared/rating-stars.css',
            '/css/shared/form.css',
            '/css/shared/modal.css',
            '/css/shared/modal-dialog.css',
            '/css/shared/header/header.css',
            '/css/shared/header/search.css',
            '/css/shared/header/notifications.css',
            '/css/shared/header/cart-preview.css',
            '/css/shared/footer.css',
            '/css/shared/auth-form.css',
            '/css/shared/confirm-modal.css',
            '/css/shared/toast.css',
            '/css/pages/user/user.css',
            '/css/shared/address-card.css',
            '/css/shared/product-card.css',
            '/css/shared/pagination.css',
            '/css/shared/empty-state.css',
            '/css/pages/user/profile.css',
            '/css/pages/user/purchase.css',
            '/css/pages/user/purchase/return-modal.css',
            '/css/pages/user/purchase/review-modal.css',
            '/css/pages/user/address.css',
            '/css/pages/user/password.css',
            '/css/pages/user/privacy.css',
            '/css/pages/user/notifications.css',
            '/css/pages/user/wishlist.css',
        ],
        entryScript: '/js/pages/user/user.js',
    },
    admin: {
        styles: [
            '/css/shared/base.css',
            '/css/shared/grid.css',
            '/css/shared/button.css',
            '/css/shared/avatar-placeholder.css',
            '/css/shared/rating-stars.css',
            '/css/shared/form.css',
            '/css/shared/modal.css',
            '/css/shared/modal-dialog.css',
            '/css/shared/confirm-modal.css',
            '/css/shared/image-lightbox.css',
            '/css/shared/pagination.css',
            '/css/shared/empty-state.css',
            '/css/shared/toast.css',
            '/css/shared/tooltip.css',
            '/css/pages/admin/admin.css',
            '/css/pages/admin/dashboard.css',
            '/css/pages/admin/orders.css',
            '/css/pages/admin/products.css',
            '/css/pages/admin/reviews.css',
            '/css/pages/admin/app-logs.css',
            '/css/pages/admin/users.css',
            '/css/pages/admin/categories.css',
        ],
        entryScript: '/js/pages/admin/admin.js',
    },
});

function applyViewConfig(res, name, overrides = {}) {
    Object.assign(
        res.locals,
        VIEW_CONFIGS[name] || {},
        overrides,
    );
}

export { applyViewConfig };
